env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
database_url: "host=localhost user=postgres password=canonfpa dbname=express-calc sslmode=disable"
workers: 5
timeouts:
  process_interval: 10s
  operation_sum: 20s
  operation_sub: 25s
  operation_mul: 27s
  operation_div: 30s
http_server:
  address : "localhost:8080"
  timeout: 4s
  idle_timeout: 60s