env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
database_url: "host=localhost user=postgres password=canonfpa dbname=express-calc sslmode=disable"
timeouts:
  process_interval: 60s
  operation_sum: 200s
  operation_sub: 205s
  operation_mul: 210s
  operation_div: 220s
http_server:
  address : "localhost:8080"
  timeout: 4s
  idle_timeout: 60s